### PR TITLE
Update widget_macro.md

### PR DESCRIPTION
**Pull request by tronta**
What do you think about that? "Only the implementation is different" is quite unspecific :smile:

### CODE REVIEW

**Comment by AaronErhardt** [comment]
Good idea. Maybe plural? widgets?

**Comment by tronta** [comment]
This probably exceeds my knowledge about widgets. But after rethinking, are we actually implementing any? Aren't we combining widgets to create the application screen?

**Comment by AaronErhardt** [comment]
> Only the implementation of the view is different

I totally forgot this PR, sorry. But I agree, using the word "view" sounds like a good idea in this context.

**Comment by tronta** [comment]
Do you want to merge it? Is something still missing in you point of view?

**Comment by AaronErhardt** [comment]
Yes, I'd merge it. Yet, I would prefer using the word "view" but if it would be a lot of effort for you to change this you can just close this PR and I will send a patch myself.

**Pull request closed without merging**
