### PR TITLE
Update components.md

### PR DESCRIPTION
**Pull request by tronta**
What do you think about this?
Does it make sense to link directly the file? What is the reason, why you just mention the example file in the text?

What about changing the header?

### CODE REVIEW

**Comment by AaronErhardt** [comment]
I thought the links to relm4-examples might be useful because they allow an easier setup. You just clone the repo and then you can run almost all of the examples used in the book. I should probably make this more clear, though. Should the book contain a hint that most examples can be found and run from there? Should it be in the introduction or the first chapter? What do you think?

**Comment by tronta** [comment]
Yes, I would suggest to explain in the introduction where to find the examples and how to clone them and later just put in the link to the relevant file. Then one could open it with one click.

**Comment by AaronErhardt** [comment]
I've added this to the introduction: https://aaronerhardt.github.io/relm4-book/book/#examples
And this to every chapter with an example: https://aaronerhardt.github.io/relm4-book/book/first_app.html#your-first-app

What do you think?

**Comment by tronta** [comment]
That's pretty cool! I like it 👍

**Comment by AaronErhardt** [comment]
Alright, I'll close this PR then.

**Pull request closed without merging**
