### PR TITLE
Moving example to the beginning

### PR DESCRIPTION
**Pull request by tronta**
What do you think about introducing the app to be implemented at the beginning?
I would pick the dark theme, as most IT guys use editors with dark theme anyway (afaik).

### CODE REVIEW

**Comment by AaronErhardt** [comment]
I like this approach, but I wonder wonder if it's till better to have both themes. 

As you said, programmers tend to prefer dark themes because they are easier on the eyes but the light theme is still the default theme for GTK4 application. Also showing that GTK supports different themes is nice.

I'd be great if mdbook would render the images next to each other if the width of the page is large enough, similar to the README on GitHub. I think the only only downside of using both themes is that the images are aligned a bit odd.

**Comment by tronta** [comment]
I personally would put some examples with both themes on the first page to show case that.
But than I think it's more about, what will I have achieved when I'm done after this chapter.

**Comment by AaronErhardt** [comment]
Yeah, that's a good idea. Let's keep both screenshots in the first chapter or the introduction and for the rest we'll use only the dark variant.

The only thing that needs to be changed in this PR then is the description of the images as "App screenshot light".

**Comment by tronta** [comment]
Good catch. What about this? I wouldn't emphasize the the dark schema.

**Comment by AaronErhardt** [comment]
Thanks!

**Pull request merged**
