### PR TITLE
Update factory_position.md

### PR DESCRIPTION
**Pull request by tronta**
Is this correct? I

### CODE REVIEW

**Comment by AaronErhardt** [comment]
It's basically correct, but you could theoretically also specify the width and height (how much rows and columns the widget takes).

Also I would put it a little different:

"The task of the position function is mainly to map the index to a specific position (x, y, width and height) of a factory widget inside the parent widget (view)."

**Comment by tronta** [comment]
What about area?

**Comment by AaronErhardt** [comment]
What do you mean with area?

**Comment by tronta** [comment]
The task of the position function is mainly to map the index to a specific **area** (x, y, width and height) of a factory widget inside the parent widget (view).

I mean something with width and height is an area, isn't it?

**Comment by AaronErhardt** [comment]
Oh, yeah technically you're right. But maybe position is still easier to understand? Because area in this case means only a part of the area of the grid which is not really intuitive, I guess.

**Comment by tronta** [comment]
My personal intuition is that the  position is only x, y. But maybe to not only repeat the function name, we could also provide an alternative word.
Maybe location could also be a good additional description, what do you think?
We could also write position/location, position/area…

**Comment by AaronErhardt** [comment]
Yeah, I think writing position/area is probably the best solution.

**Comment by AaronErhardt** [comment]
Perfect :+1:

**Pull request merged**
